### ISSUE TITLE
DAB files in downloads

### ISSUE THREAD

**Issue by jpinero** [FunctionLab/flib#5]
The Gold Standard files in the downloads page are .dab files. Is it possible to have them as .tsv files?
thanks!
janet

**Comment by dhimmel** [comment]
For reference, @jpinero is talking about the files at http://giant.princeton.edu/download/ corresponding to https://doi.org/10.1038/ng.3259.

"Top Edges" and "Full Network" are available as gzipped TSVs, which is a user friendly and portable format. However, "Gold Standard" is only available in a gzipped DAB file, which is a binary encoding that is not directly readable by most data science applications.

Tagging @aaronkw and @cgreene: one of them should be able to help.

**Comment by cgreene** [comment]
@jpinero / @dhimmel : I don't have access to the server, but after extracting dab files, the [`dat.py`](https://github.com/FunctionLab/flib/blob/c3bdd51080ffab65b0f2cff4a472e43064cd9b81/dat.py) script in this repository will convert them to either an edge list (termed `DAT`) or matrix (termed `PCL`).

I would support these being put up for download - I just can't do it. Hopefully this will get the files for you!

I think we updated `dat.py` to be python 2/3 compatible not that long ago.

**Comment by jpinero** [comment]
Thanks, @dhimmel for actually explaining my problem.

@dhimmel and @cgreene: I ran the dat.py script as you both suggested, like this: 

```
python dat.py -i liver.dab -o test.dat -v
```

and also

```
python dat.py -i liver.dab -o test.pcl
```

I got the following output 

```
DEBUG:__main__:Args: Namespace(dab='liver.dab', out='test.dat', verbose=True)
DEBUG:__main__:Opening liver.dab
DEBUG:__main__:Expecting 4730 genes.
DEBUG:__main__:Read 0 gene names.
DEBUG:__main__:Got 4730 genes.
and the head on bash of the file test.dat is 
b'\x002\x008\x005\x005\x009\x000'	b'\x008\x004\x001\x005\x009'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x001\x008\x003'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x001\x002\x004\x000\x005\x006'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x005\x003\x004\x000'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x001\x003\x008\x006'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x001\x002\x008\x005'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x003\x005\x001'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x008\x000\x007\x008\x001'	1.0
b'\x002\x008\x005\x005\x009\x000'	b'\x001\x001\x000\x004\x007'	1.0
```

What am I doing wrong? 
the problem is that the "Top Edges" and "Full Network" are huge, and I can't built a network in R. 
thanks a lot!

**Comment by dhimmel** [comment]
> the problem is that the "Top Edges" and "Full Network" are huge

If you want the GIANT predictions (which I assume you do), "Gold Standard" won't do the job.

How I'd approach the situation is to filter "Top Edges" even further so it's less huge. You can do it iteratively in python so memory is not an issue. I can write a python script that will do this for you, if you'd like. Just let me know if that'd be helpful.

Regardless of @jpinero's needs, I think it still makes sense to host the TSV gold standard files. @cgreene who is in the position to make this happen? Can you assign that person to this issue?

**Comment by jpinero** [comment]
@dhimmel It would be just great if you could suggest a value of posterior probability I could use as cut-off. I really liked my results from the web interface. :)

**Comment by cgreene** [comment]
@jpinero : web interface uses 0.5. 

I assigned @aaronkw and @atadych - I think one of them would be able to make it work. Error appears to be an issue from the python3ification of the script. I'll poke at it.

**Comment by cgreene** [comment]
Not entirely sure what's going on. Encoding bits look reasonable to me at a first pass. The various functions to produce files from this program are a bit distinct from what I'd usually use (e.g. they seem to use print in ways that I avoid). I don't have time to dig into the strange behavior at the moment. It appears to be printing bytestrings.

**Comment by aaronkw** [comment]
I've made the standards available as text files, updated on the downloads page.

**Comment by atadych** [comment]
I am looking into it and there are some problems with converting byte strings into string
